name: 02 - Workflow Evemts

on: 
  - push
  - pull_request
  - schedule: */5 * * * *
  - workflow_dispatch

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Display the trigger
        run: |
          echo "This workflow was triggerred by ${{github.event_name}}"
            