name: 02 - Workflow Evemts

on: 
  pull_request:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Display the trigger
        run: |
          echo "This workflow was triggerred by ${{github.event_name}}"
            